export { default as Home } from './Home'
export { default as Rules } from './Rules'
export { default as Results } from './Results'
export { default as Signup } from './Signup'
export { default as Login } from './Login'